import Head from 'next/head'
import { useRouter } from 'next/router'
import React, {useState,useEffect} from 'react'
import styles from '../styles/Home.module.css'
import ComputerGame from '../components/pages/ComputerGame'
import EnterScreen from '../components/pages/EnterScreen'
import Header from '../components/Header'
import Footer from '../components/Footer'
import { useAuth } from '../contexts/AuthContext';
import { db,comeBack } from "../firebase"
import { ref } from "firebase/database";
import { useListVals } from 'react-firebase-hooks/database';

//i did this component because of uselist doesnt work without but i dont like this way
export default function Home () {
  const { user } = useAuth();
  const router = useRouter();

  useEffect(() => {
      !user && router.push("/login")
  })

  return (
    <div>
      {user && <Pages/>}
    </div>
  );
};

 const Pages = () => {
  const [gameType,setGameType] = useState("")
  const [inGame,setInGame] = useState(false)
  const { user } = useAuth();
  const [values, loading, error] = useListVals(ref(db, 'players/' + user.uid));

  const selectGameType = (gameT) => {
    setGameType(gameT)
  }
  useEffect(() => {
    comeBack()
  },[])


  useEffect(() => {
    if(values[1]){
      setInGame(true)
    }else{
      setInGame(false)
    }
  },[values])

  return (
    <div className={styles.container}>
      <Head>
        <title>RSP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <div className={styles.main}>
        <div>
        {inGame ? <ComputerGame user={user} setInGame={setInGame} /> :
        <EnterScreen playWith={selectGameType} user={user}/>}
        </div>
      </div>
      <Footer/>
    </div>
  )
}